sudo: required

services:
  - docker

env:
  - NODE_VERSION=latest
  - NODE_VERSION=0.12
  - NODE_VERSION=0.12.7
  - NODE_VERSION=4
  - NODE_VERSION=4.1
  - NODE_VERSION=4.1.1
  - NODE_VERSION=4.2
  - NODE_VERSION=4.2.0

script:
  - make build-$NODE_VERSION
  - make test-all-$NODE_VERSION