sudo: required

services:
  - docker

env:
  - NODE_VERSION=latest
  - NODE_VERSION=0.12
  - NODE_VERSION=0.12.9
  - NODE_VERSION=4
  - NODE_VERSION=4.2
  - NODE_VERSION=4.2.3
  - NODE_VERSION=5
  - NODE_VERSION=5.2
  - NODE_VERSION=5.2.0

script:
  - make build-$NODE_VERSION
  - make test-all-$NODE_VERSION

deploy:
  provider: script
  script: docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-$NODE_VERSION
  on:
    repo: 'umweltdk/docker-node'
    branch: master
