sudo: required

services:
  - docker

env:
  - NODE_VERSION=latest
  - NODE_VERSION=lts
  - NODE_VERSION=old

script:
  - make build-$NODE_VERSION
  - make test-all-$NODE_VERSION

deploy:
  provider: script
  script: docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-$NODE_VERSION
  on:
    repo: 'umweltdk/docker-node'
    branch: master
