FROM umweltdk/node-builder-base:0.12

ONBUILD COPY package.json /usr/src/app/
ONBUILD RUN npm install

ONBUILD COPY bower.json /usr/src/app/
ONBUILD RUN ./node_modules/.bin/bower install

ONBUILD COPY . /usr/src/app/
ONBUILD USER root
ONBUILD RUN  cp -R /usr/src/app /usr/src/app-copy \
  && rm -r /usr/src/app \
  && mv /usr/src/app-copy /usr/src/app \
  && chown -R app:app /usr/src/app
ONBUILD USER app

ONBUILD RUN ! jq -e .scripts.build package.json > /dev/null || npm run build
