FROM umweltdk/node:0.12

ONBUILD COPY package.json *ackage-lock.json /usr/src/app/
ONBUILD RUN npm install --unsafe-perm

ONBUILD COPY . /usr/src/app/
ONBUILD RUN ! jq -e .scripts.build package.json > /dev/null || npm run build
