FROM umweltdk/node:0.12

ONBUILD COPY package.json /usr/src/app/
ONBUILD RUN npm install --unsafe-perm

ONBUILD COPY bower.json /usr/src/app/
ONBUILD RUN ./node_modules/.bin/bower install --allow-root

ONBUILD COPY . /usr/src/app/

ONBUILD RUN ! jq -e .scripts.build package.json > /dev/null || npm run build
